import { Platform, StyleSheet } from "react-native";

export const SURFACE = {
  background: "#120d0a",
  backdropA: "#2a1a11",
  backdropB: "#1b120d",
  shell: "#1c130d",
  frame: "#26180f",
  line: "#4f3523",
  text: "#f5e7cf",
  muted: "#b79d77",
  tileDark: "#4b3119",
  tileLight: "#6a4728",
  tileTint: "rgba(255,255,255,0.035)",
  button: "#ead2a2",
  buttonText: "#1a120b",
};

export const PLAYER_THEME = {
  red: {
    label: "Jade",
    seat: "South seat",
    accent: "#79dbc7",
    piece: "#2f7e6b",
    pieceEdge: "#95f6e2",
    pieceCore: "#dcfff6",
    wash: "rgba(121,219,199,0.18)",
  },
  blue: {
    label: "Gold",
    seat: "North seat",
    accent: "#f4ca6f",
    piece: "#b77d18",
    pieceEdge: "#ffe6ad",
    pieceCore: "#fff5d2",
    wash: "rgba(244,202,111,0.16)",
  },
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: SURFACE.background },
  backdropOrb: { position: "absolute", borderRadius: 999, opacity: 0.52 },
  backdropOrbLeft: {
    width: 260,
    height: 260,
    top: -48,
    left: -72,
    backgroundColor: SURFACE.backdropA,
  },
  backdropOrbRight: {
    width: 320,
    height: 320,
    right: -120,
    top: 180,
    backgroundColor: SURFACE.backdropB,
  },
  content: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 28 },
  introContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: "center",
  },
  introStage: {
    flex: 1,
    width: "100%",
    maxWidth: 620,
    alignSelf: "center",
    justifyContent: "center",
    gap: 28,
  },
  introTopArea: {
    alignItems: "center",
    gap: 14,
  },
  header: { alignItems: "center" },
  kicker: {
    width: "100%",
    color: SURFACE.muted,
    fontSize: 11,
    letterSpacing: 3,
    textTransform: "uppercase",
    marginBottom: 8,
    textAlign: "center",
  },
  title: {
    width: "100%",
    color: SURFACE.text,
    fontSize: 42,
    lineHeight: 46,
    textAlign: "center",
    fontFamily: Platform.select({
      ios: "Georgia",
      android: "serif",
      default: undefined,
    }),
  },
  languageToggle: {
    alignSelf: "center",
    flexDirection: "row",
    gap: 6,
    padding: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.28)",
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  gameLanguageToggle: {
    marginBottom: 12,
  },
  languageOption: {
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  languageOptionActive: {
    backgroundColor: SURFACE.button,
  },
  languageOptionPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  languageOptionText: {
    color: SURFACE.text,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
  },
  languageOptionTextActive: {
    color: SURFACE.buttonText,
  },
  settingsButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.28)",
    backgroundColor: "rgba(234,210,162,0.08)",
  },
  settingsButtonIcon: {
    color: SURFACE.button,
    fontSize: 17,
    lineHeight: 20,
    fontWeight: "900",
  },
  settingsButtonText: {
    color: SURFACE.button,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  introSettingsButton: {
    position: "absolute",
    top: 18,
    right: 18,
    zIndex: 10,
    minWidth: 42,
    paddingHorizontal: 0,
  },
  burmeseEyebrow: {
    fontSize: 13,
    letterSpacing: 0,
    textTransform: "none",
  },
  subtitle: { maxWidth: 560, color: "#d7c19e", fontSize: 16, lineHeight: 24 },
  introLead: {
    color: SURFACE.text,
    fontSize: 20,
    lineHeight: 30,
    marginBottom: 12,
    maxWidth: 540,
  },
  introBody: {
    color: "#d7c19e",
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 22,
    maxWidth: 560,
  },
  rulesBlock: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: SURFACE.line,
    paddingVertical: 18,
  },
  rulesTitle: {
    color: SURFACE.text,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "700",
    marginBottom: 12,
  },
  ruleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  ruleIndex: {
    width: 30,
    color: SURFACE.muted,
    fontSize: 12,
    letterSpacing: 1.4,
    textTransform: "uppercase",
    paddingTop: 3,
  },
  ruleText: {
    flex: 1,
    color: SURFACE.text,
    fontSize: 15,
    lineHeight: 23,
  },
  menuBlock: {
    gap: 12,
  },
  introMenuArea: {
    width: "100%",
  },
  menuOption: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: SURFACE.line,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  menuOptionPressed: {
    borderColor: SURFACE.button,
    backgroundColor: "rgba(234,210,162,0.1)",
    transform: [{ scale: 0.99 }],
  },
  menuIconBubble: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(234,210,162,0.12)",
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.26)",
  },
  menuIcon: {
    fontSize: 24,
    lineHeight: 30,
  },
  menuCopy: {
    flex: 1,
    minWidth: 0,
  },
  menuLabel: {
    color: SURFACE.text,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
  },
  menuDetail: {
    color: SURFACE.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
  },
  menuArrow: {
    color: SURFACE.button,
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "300",
  },
  difficultyPanel: {
    marginTop: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.22)",
    borderRadius: 20,
    backgroundColor: "rgba(234,210,162,0.055)",
  },
  difficultyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  difficultyLabel: {
    flexShrink: 1,
    color: SURFACE.text,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  difficultyHint: {
    color: SURFACE.button,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
  },
  difficultyRow: {
    flexDirection: "row",
    gap: 8,
  },
  difficultyButton: {
    flex: 1,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SURFACE.line,
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  difficultyButtonActive: {
    borderColor: SURFACE.button,
    backgroundColor: SURFACE.button,
  },
  difficultyButtonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  difficultyButtonText: {
    color: SURFACE.text,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "800",
  },
  difficultyButtonTextActive: {
    color: SURFACE.buttonText,
  },
  onlineLobbyPanel: {
    gap: 16,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.22)",
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  onlinePrimaryButton: {
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: SURFACE.button,
  },
  onlinePrimaryButtonText: {
    color: SURFACE.buttonText,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: "900",
  },
  onlineJoinBlock: {
    gap: 9,
  },
  onlineSectionLabel: {
    color: SURFACE.muted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  onlineJoinRow: {
    flexDirection: "row",
    gap: 10,
  },
  onlineCodeInput: {
    flex: 1,
    minHeight: 50,
    color: SURFACE.text,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: "900",
    letterSpacing: 2,
    textAlign: "center",
    borderWidth: 1,
    borderColor: SURFACE.line,
    borderRadius: 14,
    backgroundColor: "rgba(0,0,0,0.18)",
    paddingHorizontal: 12,
  },
  onlineJoinButton: {
    minWidth: 84,
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: "rgba(234,210,162,0.15)",
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.35)",
  },
  onlineJoinButtonText: {
    color: SURFACE.button,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  onlineResumeBlock: {
    gap: 10,
    paddingTop: 14,
    borderTopWidth: 1,
    borderColor: SURFACE.line,
  },
  onlineResumeText: {
    color: SURFACE.text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  onlineResumeActions: {
    flexDirection: "row",
    gap: 10,
  },
  onlineSecondaryButton: {
    flex: 1,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: "rgba(234,210,162,0.14)",
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.34)",
  },
  onlineSecondaryButtonText: {
    color: SURFACE.button,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  onlineGhostButton: {
    flex: 1,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SURFACE.line,
    backgroundColor: "rgba(255,255,255,0.025)",
  },
  onlineGhostButtonText: {
    color: SURFACE.muted,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  onlineButtonDisabled: {
    opacity: 0.55,
  },
  onlineErrorText: {
    color: "#ffb4a8",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  onlineGameMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 12,
  },
  onlineGameMetaText: {
    flexShrink: 1,
    color: SURFACE.muted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "800",
  },
  settingsContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: "center",
  },
  settingsStage: {
    width: "100%",
    maxWidth: 680,
    gap: 20,
  },
  settingsPanel: {
    gap: 16,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.22)",
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  settingsSection: {
    gap: 10,
  },
  settingsSectionTitle: {
    color: SURFACE.text,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
  },
  settingsSectionText: {
    color: SURFACE.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  settingsLanguageToggle: {
    alignSelf: "flex-start",
  },
  settingsDivider: {
    height: 1,
    backgroundColor: SURFACE.line,
  },
  settingHeaderCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  settingsModeList: {
    gap: 10,
  },
  settingsModeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 54,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: SURFACE.line,
    backgroundColor: "rgba(255,255,255,0.025)",
  },
  settingsModeIcon: {
    width: 28,
    textAlign: "center",
    fontSize: 20,
    lineHeight: 24,
  },
  settingsModeTitle: {
    color: SURFACE.text,
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "900",
  },
  introHint: {
    color: SURFACE.muted,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 12,
    maxWidth: 420,
  },
  statusBand: {
    paddingVertical: 14,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: SURFACE.line,
    marginBottom: 18,
  },
  statusBandLabel: {
    color: SURFACE.muted,
    fontSize: 11,
    letterSpacing: 2.4,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 11,
    paddingHorizontal: 14,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  statusDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  statusPillText: { flex: 1, fontSize: 15, lineHeight: 22, fontWeight: "600" },
  playersGrid: { marginBottom: 24 },
  playersGridWide: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  playerStrip: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: SURFACE.line,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  playerStripHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  playerIdentity: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1,
  },
  playerPulse: { width: 12, height: 12, borderRadius: 6, marginRight: 10 },
  playerSeat: { color: SURFACE.muted, fontSize: 12, marginBottom: 2 },
  playerName: { fontSize: 26, lineHeight: 30, fontWeight: "700" },
  playerCount: { alignItems: "flex-end", marginLeft: 16 },
  playerCountValue: {
    color: SURFACE.text,
    fontSize: 28,
    lineHeight: 30,
    fontWeight: "700",
  },
  playerCountLabel: { color: SURFACE.muted, fontSize: 12, marginTop: 2 },
  trackRow: { flexDirection: "row", marginBottom: 10 },
  trackSegment: {
    flex: 1,
    height: 7,
    borderRadius: 999,
    marginRight: 5,
  },
  trackSegmentMuted: { backgroundColor: "#322117", opacity: 1 },
  playerMetaText: { color: SURFACE.muted, fontSize: 13 },
  playerMetaWinner: { fontWeight: "700" },
  seatState: { textTransform: "uppercase", letterSpacing: 1.2 },
  gameContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 26,
    alignItems: "center",
    justifyContent: "center",
  },
  gameTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  backButton: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: SURFACE.line,
    backgroundColor: "rgba(255,255,255,0.035)",
  },
  backButtonIcon: {
    color: SURFACE.button,
    fontSize: 26,
    lineHeight: 26,
    fontWeight: "500",
  },
  backButtonText: {
    color: SURFACE.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "800",
  },
  modeBadge: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 1,
    maxWidth: "64%",
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(234,210,162,0.28)",
    backgroundColor: "rgba(234,210,162,0.08)",
  },
  modeBadgeIcon: {
    fontSize: 16,
    lineHeight: 19,
  },
  modeBadgeText: {
    flexShrink: 1,
    color: SURFACE.button,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
  },
  stateCluster: {
    width: "100%",
    alignItems: "center",
    marginBottom: 14,
  },
  stateLabel: {
    color: SURFACE.muted,
    fontSize: 11,
    letterSpacing: 2.4,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  seatSpacerTop: { marginBottom: 14 },
  seatSpacerBottom: { marginTop: 14 },
  workspace: { marginBottom: 24 },
  workspaceWide: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  boardColumn: { alignItems: "flex-start" },
  boardHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionEyebrow: {
    color: SURFACE.muted,
    fontSize: 11,
    letterSpacing: 2.2,
    textTransform: "uppercase",
    marginBottom: 5,
  },
  sectionTitle: {
    color: SURFACE.text,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "700",
  },
  boardBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginLeft: 12,
  },
  boardBadgeText: { fontSize: 12, fontWeight: "700", letterSpacing: 0.4 },
  boardShell: {
    padding: 14,
    borderRadius: 28,
    backgroundColor: SURFACE.shell,
    borderWidth: 1,
    borderColor: SURFACE.line,
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  boardFrame: { padding: 10, borderRadius: 22, backgroundColor: SURFACE.frame },
  board: { borderRadius: 16, overflow: "hidden", flexDirection: "row", flexWrap: "wrap" },
  tile: { alignItems: "center", justifyContent: "center" },
  tileTint: { ...StyleSheet.absoluteFillObject, backgroundColor: SURFACE.tileTint },
  selectionHalo: { ...StyleSheet.absoluteFillObject, borderWidth: 2 },
  captureSourceHalo: { ...StyleSheet.absoluteFillObject, borderWidth: 1.5 },
  forcedHalo: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 2,
    borderColor: "#ead2a2",
  },
  moveTarget: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  moveTargetCore: { width: 8, height: 8, borderRadius: 4 },
  piece: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    shadowOpacity: 0.38,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    overflow: "hidden",
  },
  pieceSheen: {
    position: "absolute",
    top: 6,
    width: "66%",
    height: "22%",
    borderRadius: 999,
    opacity: 0.22,
  },
  pieceCore: { opacity: 0.5 },
  kingBadge: {
    position: "absolute",
    right: 3,
    bottom: 3,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    backgroundColor: "rgba(12,9,7,0.66)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
  },
  kingText: { color: SURFACE.text, fontSize: 10, fontWeight: "900" },
  utilityRail: {
    marginTop: 22,
    backgroundColor: "rgba(255,255,255,0.02)",
    borderWidth: 1,
    borderColor: SURFACE.line,
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  utilityRailWide: { marginTop: 42, marginLeft: 24 },
  infoSection: { paddingVertical: 14 },
  utilityDivider: { borderTopWidth: 1, borderColor: SURFACE.line },
  infoLabel: {
    color: SURFACE.muted,
    fontSize: 11,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  infoValue: { color: SURFACE.text, fontSize: 15, lineHeight: 23 },
  footerBar: { borderTopWidth: 1, borderColor: SURFACE.line, paddingTop: 18 },
  footerBarWide: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerCopy: { flex: 1, marginRight: 16, marginBottom: 16 },
  footerLabel: {
    color: SURFACE.muted,
    fontSize: 11,
    letterSpacing: 2.2,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  footerBody: { color: SURFACE.text, fontSize: 15, lineHeight: 23, maxWidth: 520 },
  actionButton: {
    backgroundColor: SURFACE.button,
    borderRadius: 999,
    paddingVertical: 16,
    paddingHorizontal: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  actionButtonPressed: { opacity: 0.88, transform: [{ scale: 0.98 }] },
  actionButtonText: {
    color: SURFACE.buttonText,
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
});
